url: https://kiwilabs.io

# Site settings
title: kiwilabs.io
email: your-email@domain.com
description: "Voice-first interactive interfaces that extends your daily routines and practices your cognitive flexibility."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/kiwilabsHQ
  - title: instagram
    url: https://www.instagram.com/kiwilabshq